import { Grant, Application, KPIData, ActivityItem, ComplianceCheck, ReviewFeedback, AuditEntry, ProposalQuestion } from '@/types';

export const mockGrants: Grant[] = [
    {
        id: 'grant-1',
        title: 'NSF Small Business Innovation Research (SBIR) Phase I',
        funder: 'National Science Foundation',
        amount: 275000,
        deadline: '2026-04-15',
        eligibility: ['US-based small business', 'Less than 500 employees', 'Principal investigator employed by company'],
        keywords: ['deep tech', 'innovation', 'R&D', 'technology commercialization'],
        fitScore: 92,
        probabilityScore: 78,
        status: 'open',
        description: 'Supports small businesses in scientific R&D with commercial potential. Phase I grants fund feasibility studies.',
        category: 'Research & Development',
    },
    {
        id: 'grant-2',
        title: 'DOE Advanced Research Projects Agency-Energy (ARPA-E)',
        funder: 'Department of Energy',
        amount: 500000,
        deadline: '2026-03-28',
        eligibility: ['US entity', 'Energy sector focus', 'Novel technology approach'],
        keywords: ['clean energy', 'climate tech', 'energy storage', 'grid modernization'],
        fitScore: 87,
        probabilityScore: 65,
        status: 'closing_soon',
        description: 'Funds transformational energy technologies that are too early for private sector investment.',
        category: 'Energy & Climate',
    },
    {
        id: 'grant-3',
        title: 'NIH Small Business Technology Transfer (STTR)',
        funder: 'National Institutes of Health',
        amount: 400000,
        deadline: '2026-05-20',
        eligibility: ['US small business', 'Partnered with research institution', 'Health-related focus'],
        keywords: ['biotech', 'health tech', 'medical devices', 'therapeutics'],
        fitScore: 74,
        probabilityScore: 62,
        status: 'open',
        description: 'Facilitates cooperative R&D between small businesses and research institutions in health sciences.',
        category: 'Health & Biotech',
    },
    {
        id: 'grant-4',
        title: 'USDA Rural Business Development Grant',
        funder: 'US Department of Agriculture',
        amount: 150000,
        deadline: '2026-06-01',
        eligibility: ['Rural area business', 'Agricultural or rural development focus'],
        keywords: ['agriculture', 'rural development', 'food systems', 'community development'],
        fitScore: 68,
        probabilityScore: 71,
        status: 'open',
        description: 'Supports targeted technical assistance, training, and small business development in rural areas.',
        category: 'Agriculture',
    },
    {
        id: 'grant-5',
        title: 'EDA Build Back Better Regional Challenge',
        funder: 'Economic Development Administration',
        amount: 750000,
        deadline: '2026-04-30',
        eligibility: ['Coalition of entities', 'Economic development focus', 'Regional impact'],
        keywords: ['economic development', 'workforce', 'infrastructure', 'regional growth'],
        fitScore: 81,
        probabilityScore: 55,
        status: 'open',
        description: 'Funds regional coalitions implementing transformative projects to rebuild and strengthen local economies.',
        category: 'Economic Development',
    },
    {
        id: 'grant-6',
        title: 'Google.org Impact Challenge: AI for Social Good',
        funder: 'Google.org',
        amount: 2000000,
        deadline: '2026-07-15',
        eligibility: ['Nonprofit or social enterprise', 'AI-powered solution', 'Global impact'],
        keywords: ['artificial intelligence', 'social impact', 'nonprofit', 'machine learning'],
        fitScore: 95,
        probabilityScore: 42,
        status: 'open',
        description: 'Supports organizations using AI to address societal challenges. Focus on scalable, impactful solutions.',
        category: 'Technology & Innovation',
    },
];

export const mockApplications: Application[] = [
    {
        id: 'app-1',
        orgId: 'org-1',
        grantId: 'grant-1',
        grantTitle: 'NSF SBIR Phase I',
        funder: 'National Science Foundation',
        status: 'in_progress',
        narrative: '',
        formData: {},
        complianceScore: 72,
        probabilityScore: 78,
        deadline: '2026-04-15',
        createdAt: '2026-03-01',
        updatedAt: '2026-03-05',
    },
    {
        id: 'app-2',
        orgId: 'org-1',
        grantId: 'grant-2',
        grantTitle: 'ARPA-E Energy Innovation',
        funder: 'Department of Energy',
        status: 'draft',
        narrative: '',
        formData: {},
        complianceScore: 45,
        probabilityScore: 65,
        deadline: '2026-03-28',
        createdAt: '2026-02-20',
        updatedAt: '2026-03-04',
    },
    {
        id: 'app-3',
        orgId: 'org-1',
        grantId: 'grant-6',
        grantTitle: 'Google.org AI for Social Good',
        funder: 'Google.org',
        status: 'submitted',
        narrative: '',
        formData: {},
        complianceScore: 96,
        probabilityScore: 42,
        deadline: '2026-07-15',
        createdAt: '2026-01-15',
        updatedAt: '2026-03-01',
    },
];

export const mockKPIs: KPIData[] = [
    { label: 'Total Grants Found', value: 147, change: 12.5, icon: 'search', suffix: '' },
    { label: 'Applications In Progress', value: 8, change: 33.3, icon: 'file-text', suffix: '' },
    { label: 'Avg Fit Score', value: 82, change: 5.2, icon: 'target', suffix: '%' },
    { label: 'Potential Funding', value: 4.2, change: 18.7, prefix: '$', icon: 'dollar-sign', suffix: 'M' },
];

export const mockActivity: ActivityItem[] = [
    { id: 'act-1', action: 'Narrative Generated', agent: 'Narrative Agent', timestamp: '2 min ago', details: 'Generated proposal for NSF SBIR Phase I' },
    { id: 'act-2', action: 'Compliance Check', agent: 'Compliance Guard', timestamp: '15 min ago', details: 'ARPA-E application scored 45% — 3 warnings' },
    { id: 'act-3', action: 'Grant Discovered', agent: 'Discovery Agent', timestamp: '1 hr ago', details: 'Found 12 new matching grants in climate tech' },
    { id: 'act-4', action: 'Eligibility Verified', agent: 'Eligibility Agent', timestamp: '2 hrs ago', details: 'Confirmed eligibility for NIH STTR program' },
    { id: 'act-5', action: 'Review Simulated', agent: 'Reviewer Simulator', timestamp: '3 hrs ago', details: 'Google.org proposal scored 8.4/10 by AI reviewer' },
    { id: 'act-6', action: 'Form Auto-filled', agent: 'Auto-Fill Agent', timestamp: '5 hrs ago', details: 'Pre-filled 23 fields for USDA application' },
];

export const mockComplianceChecks: ComplianceCheck[] = [
    { id: 'cc-1', category: 'Document Requirements', label: 'Budget Narrative', status: 'pass', message: 'Budget narrative is complete and within limits' },
    { id: 'cc-2', category: 'Document Requirements', label: 'Letter of Support', status: 'warning', message: 'Missing institutional letter of support', suggestion: 'Request letter from partner university by March 20' },
    { id: 'cc-3', category: 'Eligibility', label: 'Organization Size', status: 'pass', message: 'Team size (12) is under 500 employee limit' },
    { id: 'cc-4', category: 'Eligibility', label: 'US-based Entity', status: 'pass', message: 'Organization is registered in California, US' },
    { id: 'cc-5', category: 'Content Limits', label: 'Project Narrative', status: 'warning', message: 'Word count (4,850) exceeds recommended 4,500 words', suggestion: 'Reduce methodology section by ~350 words' },
    { id: 'cc-6', category: 'Content Limits', label: 'Abstract', status: 'pass', message: 'Abstract is 245 words (limit: 250)' },
    { id: 'cc-7', category: 'Budget', label: 'Budget Ceiling', status: 'fail', message: 'Total budget ($285,000) exceeds $275,000 limit', suggestion: 'Reduce equipment costs or travel by $10,000' },
    { id: 'cc-8', category: 'Budget', label: 'Indirect Cost Rate', status: 'pass', message: 'Indirect rate (42%) is within negotiated agreement' },
];

export const mockReviewFeedback: ReviewFeedback[] = [
    {
        id: 'rf-1',
        section: 'Project Summary',
        score: 9,
        maxScore: 10,
        feedback: 'Clearly articulates the problem and proposed solution. Strong alignment with funder priorities.',
        strengths: ['Clear problem statement', 'Measurable outcomes defined', 'Aligns with NSF mission'],
        weaknesses: ['Could mention broader impacts more explicitly'],
    },
    {
        id: 'rf-2',
        section: 'Technical Approach',
        score: 8,
        maxScore: 10,
        feedback: 'Sound methodology with innovative elements. Feasibility is well-demonstrated.',
        strengths: ['Novel technical approach', 'Clear milestones', 'Strong preliminary data'],
        weaknesses: ['Risk mitigation could be more detailed', 'Timeline may be ambitious'],
    },
    {
        id: 'rf-3',
        section: 'Team & Capabilities',
        score: 7,
        maxScore: 10,
        feedback: 'Strong PI qualifications. Team composition is adequate but could be stronger.',
        strengths: ['PI has relevant expertise', 'Prior successful projects'],
        weaknesses: ['Missing key technical hire', 'Advisory board not yet formed'],
    },
    {
        id: 'rf-4',
        section: 'Budget Justification',
        score: 8,
        maxScore: 10,
        feedback: 'Well-justified expenses. Clear connection between costs and project activities.',
        strengths: ['Detailed line items', 'Reasonable cost estimates'],
        weaknesses: ['Equipment costs could use more detail'],
    },
];

export const mockAuditLog: AuditEntry[] = [
    { id: 'al-1', action: 'Grant Discovery', agent: 'Discovery Agent', timestamp: '2026-03-06T09:00:00Z', inputSummary: 'Keywords: AI, climate tech, energy', outputSummary: 'Found 12 matching grants from Grants.gov' },
    { id: 'al-2', action: 'Eligibility Check', agent: 'Eligibility Agent', timestamp: '2026-03-06T09:15:00Z', inputSummary: 'Org profile vs NSF SBIR requirements', outputSummary: 'Eligible: 92% confidence. All criteria met.' },
    { id: 'al-3', action: 'Narrative Generation', agent: 'Narrative Agent', timestamp: '2026-03-06T09:30:00Z', inputSummary: 'Grant: NSF SBIR, Section: Project Summary', outputSummary: 'Generated 245-word project summary. Tone: Professional.' },
    { id: 'al-4', action: 'Compliance Check', agent: 'Compliance Guard', timestamp: '2026-03-06T10:00:00Z', inputSummary: 'Application app-1 full validation', outputSummary: '6 pass, 2 warnings, 1 fail. Score: 72%' },
    { id: 'al-5', action: 'Review Simulation', agent: 'Reviewer Simulator', timestamp: '2026-03-06T10:15:00Z', inputSummary: 'Full proposal for NSF SBIR', outputSummary: 'Overall score: 8.0/10. Recommend: minor revisions.' },
];

export const mockProposalQuestions: ProposalQuestion[] = [
    {
        id: 'pq-1',
        question: 'Describe the problem your project addresses and its significance.',
        answer: 'Access to non-dilutive funding remains one of the most significant barriers for early-stage deep tech startups. While billions in grant funding are available annually through federal programs like SBIR/STTR, fewer than 20% of eligible companies apply due to the complexity of the application process. Our platform, GrantAgent, leverages multi-agent AI to democratize access to grant funding by automating discovery, eligibility assessment, narrative generation, and compliance validation.',
        wordCount: 68,
        maxWords: 300,
        status: 'approved',
        tone: 'professional',
    },
    {
        id: 'pq-2',
        question: 'What is your proposed approach or methodology?',
        answer: 'GrantAgent employs a multi-agent architecture powered by large language models to orchestrate the grant application lifecycle. The Discovery Agent queries federal databases in real-time, while the Eligibility Agent cross-references organizational profiles against grant requirements using vector similarity matching. The Narrative Agent generates tailored proposals using few-shot learning from successful past applications, and the Compliance Guard validates submissions against funder-specific checklists before final review.',
        wordCount: 65,
        maxWords: 500,
        status: 'draft',
        tone: 'technical',
    },
    {
        id: 'pq-3',
        question: 'Describe the qualifications of the project team.',
        answer: 'Our founding team combines deep expertise in AI/ML engineering, grant administration, and startup operations. The PI holds a PhD in Computer Science from Stanford with specialization in NLP and has led three prior federally-funded research projects. Our CTO previously built automated document processing systems at a Fortune 500 company. We are supported by an advisory board including former NSF program directors and successful SBIR recipients.',
        wordCount: 67,
        maxWords: 300,
        status: 'edited',
        tone: 'compelling',
    },
    {
        id: 'pq-4',
        question: 'What are the expected outcomes and broader impacts?',
        answer: 'GrantAgent will enable 10x more startups to successfully apply for federal grants within 2 years of launch. By reducing the time to complete a grant application from 120+ hours to under 10 hours, we project that at least 5,000 additional small businesses will access non-dilutive funding annually. Broader impacts include increased diversity in STEM funding, as our platform removes barriers that disproportionately affect minority-led and first-time applicant organizations.',
        wordCount: 71,
        maxWords: 400,
        status: 'draft',
        tone: 'narrative',
    },
];

export const mockPipelineData = [
    { name: 'Discovered', value: 147, fill: '#00D4FF' },
    { name: 'Eligible', value: 89, fill: '#00FFA3' },
    { name: 'In Progress', value: 8, fill: '#7C3AED' },
    { name: 'Submitted', value: 3, fill: '#F59E0B' },
    { name: 'Awarded', value: 1, fill: '#10B981' },
];

export const mockProbabilityData = [
    { name: 'Jan', score: 62 },
    { name: 'Feb', score: 68 },
    { name: 'Mar', score: 75 },
    { name: 'Apr', score: 82 },
    { name: 'May', score: 78 },
    { name: 'Jun', score: 85 },
];
